package openti;
public class ID {
	public static final String ID_OSC_TESTCONTROL="ID_OSC_TESTCONTROL";
	public static final String ID_OSC_TESTCONTROL_START="ID_OSC_TESTCONTROL_START";
	public static final String ID_OSC_TESTCONTROL_STOP="ID_OSC_TESTCONTROL_STOP";
	public static final String ID_OTDR_TESTCONTROL="ID_OTDR_TESTCONTROL";
	public static final String ID_OTDR_TESTCONTROL_START="ID_OTDR_TESTCONTROL_START";
	public static final String ID_OTDR_TESTCONTROL_STOP="ID_OTDR_TESTCONTROL_STOP";
	public static final String ID_OSC_EYEDIAGRAM="ID_OSC_EYEDIAGRAM";
	public static final String ID_OTDR_TABLE="ID_OTDR_TABLE";
	public static final String ID_APPLICATION="ID_APPLICATION";
	public static final String ID_APPLICATION_OTDR="ID_APPLICATION_OTDR";
	public static final String ID_APPLICATION_SQA="ID_APPLICATION_SQA";
	public static final String ID_OTDR_ERROR="ID_OTDR_ERROR";
	public static final String ID_OTDR_ERROR_NOERROR="ID_OTDR_ERROR_NOERROR";
	public static final String ID_OTDR_ERROR_HARDWARE="ID_OTDR_ERROR_HARDWARE";
	public static final String ID_OTDR_PULSEWIDTH="ID_OTDR_PULSEWIDTH";
	public static final String ID_OTDR_PULSEWIDTH_1NS="ID_OTDR_PULSEWIDTH_1NS";
	public static final String ID_OTDR_PULSEWIDTH_10NS="ID_OTDR_PULSEWIDTH_10NS";
	public static final String ID_OTDR_PULSEWIDTH_20NS="ID_OTDR_PULSEWIDTH_20NS";
	public static final String ID_OTDR_PULSEWIDTH_50NS="ID_OTDR_PULSEWIDTH_50NS";
	public static final String ID_OTDR_PULSEWIDTH_100NS="ID_OTDR_PULSEWIDTH_100NS";
	public static final String ID_OTDR_PULSEWIDTH_500NS="ID_OTDR_PULSEWIDTH_500NS";
	public static final String ID_OTDR_AVERAGETIME="ID_OTDR_AVERAGETIME";
	public static final String ID_OTDR_TRACE="ID_OTDR_TRACE";
	public static final String ID_OTDR_DISTANCERANGE="ID_OTDR_DISTANCERANGE";
	public static final String ID_OTDR_DISTANCERANGE_1KM="ID_OTDR_DISTANCERANGE_1KM";
	public static final String ID_OTDR_DISTANCERANGE_10KM="ID_OTDR_DISTANCERANGE_10KM";
	public static final String ID_OTDR_DISTANCERANGE_20KM="ID_OTDR_DISTANCERANGE_20KM";
	public static final String ID_OTDR_DISTANCERANGE_50KM="ID_OTDR_DISTANCERANGE_50KM";
	public static final String ID_OTDR_DISTANCERANGE_100KM="ID_OTDR_DISTANCERANGE_100KM";
}
